<?php $title = 'Admin Dashboard'?>

<?php $users = $data['users'];?>
<?php $articles = $data['articles'];?>
<pre><?php var_dump($users)?></pre>
<pre><?php var_dump($articles)?></pre>


<div class="container mt-5">
    <h1 class="text-center"><?php echo $title; ?></h1>

    <div class="row">
        <div class="col-md-6 mb-4">
            <div class="card">
                <img src="https://images.pexels.com/photos/8088443/pexels-photo-8088443.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="card-img-top" alt="users">
                <div class="card-body text-center">
                    <h5 class="card-title">Users</h5>
                    <div class="mb-3">
                        <a href="?page=admin&action=manageUsers" class="btn btn-info">Manage Users</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6 mb-4">
            <div class="card">
                <img src="https://images.pexels.com/photos/2333332/pexels-photo-2333332.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="card-img-top" alt="articles">
                <div class="card-body text-center">
                    <h5 class="card-title">Articles</h5>
                    <div class="mb-3">
                        <a href="?page=admin&action=manageArticles" class="btn btn-info">Manage Articles</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6 mb-4">
            <div class="card">
                <img src="https://images.pexels.com/photos/1111368/pexels-photo-1111368.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="card-img-top" alt="comments">
                <div class="card-body text-center">
                    <h5 class="card-title">Comments</h5>
                    <div class="mb-3">
                        <a href="?page=admin&action=manageArticles" class="btn btn-info">Manage Comments</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

