<?php $title = 'Admin Manage Users'?>
<?php $users = $data['users'];?>
    <h1 class="mb-4">Manage Users</h1>
    <a href="?page=admin&action=admin_addUser" class="btn btn-primary m-1">Add User</a>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Email</th>
                <th>Role</th>
                <th>Date Registered</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user): ?>
                <tr>
                    <td><?= $user['id'] ?></td>
                    <td><?= $user['username'] ?></td>
                    <td><?= $user['email'] ?></td>
                    <td><?= $user['roles'] ?></td>
                    <td><?= $user['date_register'] ?></td>
                    <td>
                        <a href="?page=admin&action=admin_EditUser&id=<?= $user['id'] ?>" class="btn btn-success m-1">Update</a>
                        <a href="?page=admin&action=admin_deleteUser&id=<?= $user['id'] ?>" class="btn btn-danger m-1">Delete</a>
                        <a href="javascript:deleteUser(<?= $user['id'] ?>)" class="btn btn-warning m-1">Delete? (confirmJS)</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script>
  function deleteUser(id){
    const question = window.confirm("Are you sure you want to delete "+id+" ?");
    if (question){
      location.href="?page=admin&action=admin_deleteUser&id="+id;
    }
  }
</script>


    <a href="?page=admin&action=dashboard" class="btn btn-primary m-1">Retour Admin Dashboard</a>


