<?php
var_dump($data['user']);
$user =$data['user'];
?>
<h1 class="mb-3 text-center">Admin Update Picture</h1>

<form method="POST">
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input value="<?= $user['username'] ?>" type="text" class="form-control" name="username" id="username" placeholder="username">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input value="<?= $user['email'] ?>" type="text" class="form-control" name="email" id="email" placeholder="email">
    </div>



<div class="form-check mt-3">
      <input class="form-check-input" type="checkbox" id="role_member" name="role" value="ROLE_MEMBER">
      <label class="form-check-label" for="role_member">ROLE_MEMBER</label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="role_editor" name="role" value="ROLE_MEMBER,ROLE_EDITOR">
      <label class="form-check-label" for="role_editor">ROLE_EDITOR</label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="role_admin" name="role" value="ROLE_MEMBER,ROLE_EDITOR,ROLE_ADMIN">
      <label class="form-check-label" for="role_admin">ROLE_ADMIN</label>
    </div>


    <div class="mb-3">
        <input type="submit" class="btn btn-primary" name="submit" value="Edit Profile">
    </div>
</form>
