<?php $title = "Admin Add User" ?>
<?php
$errors = $data['errors'];
$userAdded = $data['userAdded'];
?>

<h1>Admin Add User</h1>
<?php if (!empty($errors)) : ?>
    <div class="alert alert-danger" role="alert">
        <?php foreach ($errors as $error) : ?>
            <p><?= $error ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>


<?php if (!$userAdded) : ?>
    <form method="POST">
        <div class="mb-3">
            <label for="username" class="form-label">Name</label>
            <input type="text" required class="form-control" id="username" name="username" placeholder="Your name">

            <label for="email" class="form-label">Email</label>
            <input type="email" required class="form-control" id="email" name="email" placeholder="Your email">

            <label for="password" class="form-label">Password</label>
            <input type="password" required class="form-control" id="password" name="password" placeholder="Your password">
            <div class="form-check mt-3">
      <input class="form-check-input" type="checkbox" id="role_member" name="role" value="ROLE_MEMBER">
      <label class="form-check-label" for="role_member">ROLE_MEMBER</label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="role_editor" name="role" value="ROLE_MEMBER,ROLE_EDITOR">
      <label class="form-check-label" for="role_editor">ROLE_EDITOR</label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="role_admin" name="role" value="ROLE_MEMBER,ROLE_EDITOR,ROLE_ADMIN">
      <label class="form-check-label" for="role_admin">ROLE_ADMIN</label>
    </div>
    <button class="mt-4 btn btn-primary" type="submit" id="send" name="submit">Send</button>

        </div>
    </form>
<?php else : ?>
    <div class="alert alert-success" role="alert">
        Compte ajouté avec succès !!! 
    </div>
<?php endif; ?>
