<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        main {
            margin-top: 6rem;
        }

        img.logo {
            width: 60px;
        }

        h4.card-title {
            min-height: 6rem;
        }

        .car-img-top,
        .carousel-item img {
            aspect-ratio: 16/9;
            object-fit: cover;
        }

        #homeCarousel {
            /* max-width:700px; */
            margin: auto;
        }

        .carousel-caption {
            background-color: rgba(0, 0, 0, 0.3);
        }

        .card,
        .card-img-top,
        .btn,
        .form-control {
            border-radius: 0;
        }

        p {
            margin-bottom: 5px;
        }
    </style>
</head>

<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-lg bg-body-secondary fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img src="" alt="" class="logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <?php foreach (CONFIG_ROUTES as $key => $value) : ?>
                        <li class="nav-item">
                            <a class="nav-link <?php if ($page === $key) echo "active"; ?>" href="?page=<?= $key ?>">
                                <?= $value ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                    <?php if (isset($_SESSION['user'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link <?php if ($page === "Profile") echo "active"; ?>" href="?page=user&action=index">
                                Profile
                            </a>
                        </li>
                    <?php endif; ?>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Login
                        </a>
                        <ul class="dropdown-menu">
                            <?php if (!isset($_SESSION['user'])) : ?>

                                <li><a class="dropdown-item" href="?page=user&action=login">Log In</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="?page=user&action=register">Register</a></li>
                            <?php else : ?>
                                <?php if ($_SESSION['user']['role'] === 'admin') : ?>
                                    <li><a class="dropdown-item" href="?page=admin&action=dashboard">Admin</a></li>
                                <?php endif; ?>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="?page=signout&action=index">Logout</a></li>
                            <?php endif; ?>
                        </ul>
                    </li>
                </ul>

                <form class="d-flex" role="search">
                    <input name="page" value="search" type="hidden">
                    <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <main class="flex-shrink-0 container-fluid">
        <?= $template ?>
    </main>

    <footer class="bg-dark text-white footer mt-auto p-3">
        <section class="container-fluid text-center">
            &copy; MVP 2023
        </section>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>