<?php $title = "Register" ?>
<?php
$errors = $data['errors'];
$userAdded = $data['userAdded'];
?>

<h1>New User</h1>
<?php if (!empty($errors)) : ?>
    <div class="alert alert-danger" role="alert">
        <?php foreach ($errors as $error) : ?>
            <p><?= $error ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>


<?php if (!$userAdded) : ?>
    <form method="POST">
        <div class="mb-3">
            <label for="username" class="form-label">Name</label>
            <input type="text" required class="form-control" id="username" name="username" placeholder="Your name">

            <label for="email" class="form-label">Email</label>
            <input type="email" required class="form-control" id="email" name="email" placeholder="Your email">

            <label for="password" class="form-label">Password</label>
            <input type="password" required class="form-control" id="password" name="password" placeholder="Your password">
            <button class="mt-4 btn btn-primary" type="submit" id="send" name="submit">Send</button>
        </div>
    </form>
<?php else : ?>
    <div class="alert alert-success" role="alert">
        Compte ajouté avec succès !!! Vous pouvez vous <a href="?page=login">connecter</a> désormais.
    </div>
<?php endif; ?>
