<?php $title = "Travel's Dream"; ?>

        
<?php $articles = $data['article'];
$caroussel =$data['caroussel'];



?>
<h1>HOME</h1>




<style>
        .card-img-top {
        aspect-ratio: 16/9;
    }

    .card {
        transition: transform 1s;
    }

    .card:hover {
        transform: scale(1.02);
    }

</style>
<section class="">
    <div id="homeCarousel" class="carousel slide" data-bs-touch="true">
        <div class="carousel-indicators">
            <?php foreach ($caroussel as $key => $article) : ?>
                <button type="button" data-bs-target="#homeCarousel" data-bs-slide-to="<?= $key ?>" <?= $key === 0 ? 'class="active" aria-current="true"' : '' ?> aria-label="Slide <?= $key + 1 ?>"></button>
            <?php endforeach ?>
        </div>

        <div class="carousel-inner">
            <?php foreach ($caroussel as $key => $article) : ?>
                <div class="carousel-item <?= $key === 0 ? 'active' : '' ?>">
                    <img src="<?= $article['image_path'] ?>" class="d-block w-100" alt="<?= $article['title'] ?>">
                    <div class="carousel-caption d-none d-md-block">
                        <h5><?= $article['title'] ?></h5>
                        <p><?= $article['content'] ?></p>
                    </div>
                </div>
            <?php endforeach ?>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#homeCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#homeCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>

<section id="articlesSection" class=" bg-secondary p-2 text-dark bg-opacity-25">
    <div>
        <h1 class="text-center mt-3">Discover all the articles!</h1>

<p>Explore the recent articles:</p>
    </div>



    <div class="row row-cols-1 row-cols-md-2 g-4">
    <?php foreach ($articles as $article) : ?>
        <div class="col">

                <div class="card">
                    <img src="<?= $article['image_path'] ?>" class="card-img-top" alt="<?= $article['title'] ?>">
                    <div class="card-body">
                        <h5 class="card-title"><?= $article['title'] ?></h5>
                        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <p class="card-text"><small class="text-muted">Last updated <?= $article['date_publication'] ?></small></p>
                        <a href="index.php?action=article&id=<?= urlencode($article['id']) ?>" class="btn btn-secondary">Read me</a>

                    </div>
                </div>

        </div>

        <?php endforeach  ?>
       
    </div>

</section>



